med = float(input('Digite uma distancia em metros: '))
print()
print('A distancia de {} equivale a: ')
print('{}km'.format(med/1000))
print('{}hm'.format(med/100))
print('{}dam'.format(med/10))
print('{}dm'.format(med*10))
print('{}cm'.format(med*100))
print('{}mm'.format(med*1000))