var = input('Digite algo: ')
print('O tipo primitivo desse valor é {}.'.format(type(var)))
print('Só tem espaços? {}'.format((var).isspace()))
print('É um número? {}'.format((var).isnumeric()))
print('É alfanumérico? {}'.format((var).isalpha()))
print('Está em maiúsculas? {}'.format((var).isupper()))
print('Está em minúsculas? {}'.format((var).islower()))
print('Esta capitalizada? {}'.format((var).istitle()))
print()
var = input('Digite mais alguma coisa: ')
print('O tipo primitivo desse valor é ',type(var))
print('Só tem espaços? ',var.isspace())
print('É um número? ',var.isnumeric())
print('É alfanumérico? ',var.isalpha())
print('Está em maiúsculas? ',var.isupper())
print('Está em minúsculas? ',var.islower())
print('Esta capitalizada? ',var.istitle())
