n = int(input('Digite um número: '))
print()
print('O dobro de {} vale {}.'.format(n,n*2))
print('O triplo de {} vale {}.'.format(n,n*3))
print('A raiz quadrada de {} vale {}.'.format(n,int(n**(1/2))))