num = input('Escreva um número entre 0 e 9999 - ')
print()
print('Esse número possui {} unidades de milhar.'.format(n[0]))
print('Esse número possui {} centenas.'.format(n[1]))
print('Esse número possui {} dezenas.'.format(n[2]))
print('Esse número possui {} unidades.'.format(n[3]))